#!/bin/sh
set -eu

for mip in 2 4 8 16; do
  mkdir -p "web/mips/$mip"
done

for png in web/*.png; do
  name=$(basename "$png")

  for mip in 2 4 8 16; do
    case "$mip" in
      2)  percent="50" ;;
      4)  percent="25" ;;
      8)  percent="12.5" ;;
      16) percent="6.25" ;;
    esac

    if [ "$name" = "idmap.png" ]; then
      convert "$png" -sample "${percent}%" "web/mips/$mip/$name"
    else
      convert "$png" -scale "${percent}%" "web/mips/$mip/$name"
    fi
  done
done
